from enum import Enum


class ShipFrameSymbol(str, Enum):
    FRAME_CARRIER = "FRAME_CARRIER"
    FRAME_CRUISER = "FRAME_CRUISER"
    FRAME_DESTROYER = "FRAME_DESTROYER"
    FRAME_DRONE = "FRAME_DRONE"
    FRAME_EXPLORER = "FRAME_EXPLORER"
    FRAME_FIGHTER = "FRAME_FIGHTER"
    FRAME_FRIGATE = "FRAME_FRIGATE"
    FRAME_HEAVY_FREIGHTER = "FRAME_HEAVY_FREIGHTER"
    FRAME_INTERCEPTOR = "FRAME_INTERCEPTOR"
    FRAME_LIGHT_FREIGHTER = "FRAME_LIGHT_FREIGHTER"
    FRAME_MINER = "FRAME_MINER"
    FRAME_PROBE = "FRAME_PROBE"
    FRAME_RACER = "FRAME_RACER"
    FRAME_SHUTTLE = "FRAME_SHUTTLE"
    FRAME_TRANSPORT = "FRAME_TRANSPORT"

    def __str__(self) -> str:
        return str(self.value)
