from enum import Enum


class WaypointType(str, Enum):
    ARTIFICIAL_GRAVITY_WELL = "ARTIFICIAL_GRAVITY_WELL"
    ASTEROID = "ASTEROID"
    ASTEROID_BASE = "ASTEROID_BASE"
    ASTEROID_FIELD = "ASTEROID_FIELD"
    DEBRIS_FIELD = "DEBRIS_FIELD"
    ENGINEERED_ASTEROID = "ENGINEERED_ASTEROID"
    FUEL_STATION = "FUEL_STATION"
    GAS_GIANT = "GAS_GIANT"
    GRAVITY_WELL = "GRAVITY_WELL"
    JUMP_GATE = "JUMP_GATE"
    MOON = "MOON"
    NEBULA = "NEBULA"
    ORBITAL_STATION = "ORBITAL_STATION"
    PLANET = "PLANET"

    def __str__(self) -> str:
        return str(self.value)
